sonar.projectKey=fontem-virtuoso-sink
sonar.projectName=fontem-virtuoso-sink

sonar.sources=virtuoso_sink
sonar.tests=tests
sonar.test.inclusions=tests/**

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml

sonar.issue.ignore.multicriteria=pylintall
sonar.issue.ignore.multicriteria.pylintall.ruleKey=external_pylint:*
sonar.issue.ignore.multicriteria.pylintall.resourceKey=**/*.py
